### ISSUE TITLE
Merge "cliff-fetch-annotation" and "cliff-update-story-tags" into a single app

### ISSUE THREAD

**Issue by pypt** [mediacloud/backend#743]
Hey James!

Once you're done with the CLIFF build fixing and had enough of the turkey, could you **merge `cliff-fetch-annotation` and `cliff-update-story-tags` into a single app**?

We have those two apps, `cliff-fetch-annotation` and `cliff-update-story-tags` that use `cliff-annotator` to detect entities in input text (coming from stories):

1. `cliff-fetch-annotation`:
    1. "listens" for jobs on the `MediaWords::Job::CLIFF::FetchAnnotation` RabbitMQ queue,
    2. takes `stories_id` (ID of a row in `stories` PostgreSQL table) as a parameter,
    3. fetches its full text content from `download_texts` (IIRC),
    4. POSTs it to `cliff-annotator`,
    5. gets back a JSON response,
    6. stores the JSON response in `cliff_annotations` table, and
    7. adds a new job to `MediaWords::Job::CLIFF::UpdateStoryTags` queue for the `cliff-update-story-tags` app to do;
2. `cliff-update-story-tags`:
    1. listens for jobs on the `MediaWords::Job::CLIFF::UpdateStoryTags` RabbitMQ queue,
    2. takes `stories_id` as a parameter as well,
    3. fetches the JSON response with detected entities from `cliff_annotations` table,
    4. parses it,
    5. stores the detected entities as story's tags (in the `tags` table), and
    6. adds a new job to `MediaWords::Job::NYTLabels::FetchAnnotation` job for the similar processing to happen with `nytlabels-*` apps.

This way we end up knowing what entities (persons, geographical locations, etc.) does the story mention and we can query for them using the `tags` table.

Why is it a two-step process, i.e. why does the raw JSON response have to be stored and then fetched again later, you might ask? I don't know. When I was implementing it, I thought I had a good reason to make it that way, I think my reasoning was along the lines of "oh, we might want to store more of the stuff from the raw JSON responses in the database at a later date so we'll want to reprocess those raw responses", but we never needed to do that, and the table that stores those raw responses ended up being rather chonky and takes up precious and expensive SSD disk space:

```
mediacloud=# select pg_size_pretty(pg_relation_size('cliff_annotations'));
 pg_size_pretty 
----------------
 281 GB
(1 row)
```

(`nytlabels-*` does similar stuff, and the table is even bigger - 816 GB - but that's going to be another task to get rid of it too.)

So, you might agree that it's pointless to have two apps to do this single workflow, and it could be a single app plus save us some disk space. Could you make it so?

Things you'll need to do:

1. Come up with a good name for this new app which does both fetching and tagging. Try to avoid having the term `process` in the name - everything that we do is processing data in some way :)

2. Create a new app in `apps/` that's going to do the thing.
    * It's probably best to `cp -R` a related app to a new directory and adapt it accordingly. Docs in `docs/docker-*.markdown` might be able to help you too.
    * Here's another doc on how to create apps from scratch: https://github.com/mediacloud/backend/blob/master/doc/creating_apps.markdown
    * I'd highly recommend using PyCharm for doing Python development. It's slightly painful to do the initial setup (https://github.com/mediacloud/backend/blob/master/doc/pycharm.markdown) but IMHO it's worth it.

3. Merge `cliff-base`, `cliff-fetch-annotation`, `cliff-update-story-tags` into a single app.
    * You'll need to make appropriate changes in `apps/docker-compose.dist.yml` so that we'll know how to deploy it. For how to do it, refer to [Compose file version 3 reference](https://docs.docker.com/compose/compose-file/), but I think a simple intuition + guesswork + copy pasting approach should work well here too.
    * You'll have to deal a little with `DatabaseHandler`, our sort-of-ORM for PostgreSQL (https://github.com/mediacloud/backend/blob/master/apps/common/src/python/mediawords/db/handler.py). The nano-backstory behind this class is that we've been using a module in Perl called `DBIx::Simple`, and then when we decided that we want to move our codebase to Python, we decided to rewrite the good parts of it to Python. The class uses some weird Perl terminology (e.g. a "hash" in Perl is a `dict` in Python), but other than that I'd say it works pretty well for us.
    * Make sure tests work too. Here's how to run them: https://github.com/mediacloud/backend/blob/master/doc/dev_scripts.markdown#run_testpy---run-test-in-apps-testing-environment. Typically we'd start `cliff-annotator` itself via tested app's `docker-compose.tests.yml`, make some requests to it and see if the response is something that looks reasonable, but `cliff-annotator` takes up 6 GB of RAM to run, and our CI of choice (GitHub Workflows) just doesn't have that much, so you'll have to continue on mocking the requests and responses as is currently done in those tests.
    * If you can, abide by our coding guidelines: https://github.com/mediacloud/backend/blob/master/doc/coding_guidelines.markdown#python-version. They're not strict, I guess they could be summarized as: 1) code should be formatted to how PyCharm would like to see it formatted; 2) use typing annotations to give IDE + other programmers an idea of what kind of parameters do your functions expect and what is it that they return; 3) write at least a tiny little test for the key parts of the code.

4. Make the rest of the system add jobs to `cliff-whateveryourappiscalled` app's queue instead of `cliff-fetch-annotation` queue, i.e. replace `MediaWords::Job::CLIFF::FetchAnnotation` with something else.

4. Write a migration which `TRUNCATE`s and then `DROP`s the `cliff_annotations` table. Here's a rather terse doc on how to do that: https://github.com/mediacloud/backend/blob/master/doc/schema_migrations.markdown
    * If you downright `DROP` a table without truncating it first, PostgreSQL doesn't (always?) free up the disk space occupied by the dropped table, so do `TRUNCATE` first.
    * Sorry in advance for our home-invented migrations system; we should redo those migrations with a more modern approach (e.g. Flyway), but it is what it is for the time being.

As always, if you don't get something, it's definitely our fault, so when in doubt, ask early and ask often!

**Comment by jtotoole** [comment]
closed via https://github.com/mediacloud/backend/commit/ca8bdf225a39b60f3b2a8b7d2a9f9b3283f5ac91

**Comment by pypt** [comment]
Let's keep this open for a bit until we drop those tables: https://github.com/mediacloud/backend/pull/751

**Comment by jtotoole** [comment]
closed via https://github.com/mediacloud/backend/pull/745 and https://github.com/mediacloud/backend/pull/800
