### ISSUE TITLE
nytlabels-annotator container not building

### ISSUE THREAD

**Issue by hroberts** [mediacloud/backend#748]
the container is failing to build with the below error.  I cleaned out my whole container cache and rebuilt from scratch and still get the same error:

```
ERROR: Cannot install -r requirements.txt (line 33) and tensorboard==1.14.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

The conflict is caused by:
    The user requested tensorboard==1.14.0
    tensorflow 1.15.4 depends on tensorboard<1.16.0 and >=1.15.0
```

**Comment by jtotoole** [comment]
I ran into this a few days ago and fixed it with @pypt's endorsement by pinning `gast` at `0.2.2` and `tensorboard` at `1.15.0` in this `requirements.txt` file within `nytlabels-annotator`:

https://github.com/mediacloud/backend/pull/745/files#diff-55302376ee90018e7f2a33d81baf1027c7db86e2fb857b1adb75863e745266d3

**Comment by pypt** [comment]
@jtotoole could you fix this by cherry picking the version bump and submitting a quick PR?

**Comment by pypt** [comment]
Fixed now.
